site_name: pygsm
theme:
  name: material
  palette:
    - scheme: default
      primary: light_blue
      accent: cyan
  features:
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
repo_url: https://github.com/ZimmermanGroup/pyGSM
site_author: Cody Aldaz
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: 🔗
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
