name: rdmc_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - rdkit>=2021.03.1
  - openbabel>=3
  - py3dmol
  - ase
  - networkx
  - matplotlib
  - cclib
