target-version = "py312"
line-length = 88
fix = true
preview = true

[lint]
select = ["D", "E", "F", "I", "DOC"]
pydocstyle.convention = "numpy"
ignore = [
    "E203", # Whitespace before ':'
    "E231", # trailing whitespace
    "E501", # Line too long
]
[lint.extend-per-file-ignores]
"__init__.py" = ["F401"]
