name: Continuous Integration

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 8 * * *"
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: actions-id-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-formatting:
    name: Check Formatting Errors
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Pycodestyle
        run: |
          python -m pip install pycodestyle

      # We are under a transition from pycodestyle to more thorough checks
      # We will keep pycodestyle for rdmc
      # and use ruff and other tools for rdtools

      - name: Run pycodestyle
        run: |
          pycodestyle --statistics \
          --count \
          --max-line-length 150 \
          --max-doc-length 200 \
          --ignore=E203,E266,E501,W503,W505 \
          --show-source \
          rdmc

      - name: Install Linters, formatter, and pre-commit
        run: |
          python -m pip install '.[dev]'

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --files $(find rdtools -name "*.py")

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} Subtest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          activate-environment: rdmc_env
          environment-file: environment.yml

      - name: Install Pytest
        run: mamba install -n rdmc_env -y pytest pytest-cov nbmake # temporarily remove "pytest-check"

      - name: Mamba info
        run: |
          mamba run -n rdmc_env mamba info
          mamba run -n rdmc_env mamba list

      - name: Install RDMC
        run: mamba run -n rdmc_env python -m pip install --no-deps -vv -e ./

      - name: Run Unit Tests
        run: mamba run -n rdmc_env pytest

      - name: Test notebooks
        run: |
          mamba run -n rdmc_env pytest --no-cov -v --nbmake \
            "ipython/Conformer Generation Workflow.ipynb" \
            "ipython/Forcefield Examples.ipynb" \
            "ipython/Handle molecule with XYZ.ipynb" \
            "ipython/QM Parser Demo 1 - Built-in Parser.ipynb" \
            "ipython/QM Parser Demo 2 - General Parser.ipynb" \
            "ipython/Viewer Examples.ipynb"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
